config/routes.rb
Rails.application.routes.draw do

  root to: "static_page#root"

  resources :users, only: [:create]
  resource :session, only: [:create, :destroy, :show]

  namespace :api, defaults: { format: :json } do
  	resources :recordings, except: [:edit, :new]
  	resources :notes, only: [:create, :destroy]
    resources :keysets, except: [:edit, :new]
  end

end

app/views/layouts/_error.html.erb
<% if flash[:errors] %>
  <div class="flashAlert">
    <button class="closeFlash">&times;</button>
    <%= flash[:errors].join("<br>").html_safe %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div id="container-nav" class="clearfix">
	<section id="nav" class="group">
		<a id="navTitle" href="#"><h3>ProKeys</h3></a>
        <!-- Checkbox Hack markup -->
        <input type="checkbox" id="toggle" />
        <label for="toggle" onclick>Menu</label>
        <!-- /Checkbox Hack markup -->
        <nav>
            <ul id="left">
				<% if signed_in? %>
					<li><%= link_to "Sign Out", session_url, method: :delete, remote: true %></li>
					<li><a href="#/account">Account</a></li>
				<% else %>
					<li><a id="logInLink">Log In</a></li>
					<li><a id="signUpLink">Sign Up</a></li>
				<% end %>
            </ul>
            <ul id="right">
				<!-- <li><a href="#/posts/index">Posts</a></li> -->
				<li><a href="#/customize">Customize</a></li>
				<li><a href="#/record">Record</a></li>
				<li><a href="#/about">About</a></li>
            </ul>
        </nav>
	</section>
</div>

<div class="modal" id="logInModal">
	<div class="modal-content">
		<div class="modal-header">
			<span class="close">&times;</span>
			<h2>Log In</h2>
		</div>
		<form class="sign-in" action="/session" method="post" data-remote="true" class="form-signin">
	      	<div class="modal-body">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input id="username" name="user[username]" placeholder="Username" type="text" autofocus>
				<input id="password" name="user[password]" placeholder="Password" type="password">
	      	</div>
	  		<div class="modal-footer">
	        	<button class="close" type="button">Close</button>
	        	<input type="submit" class="Btn" id="login" value="Login »">
	  		</div>
		</form>
	</div>
</div>

<div class="modal" id="signUpModal">
    <div class="modal-content">
    	<div class="modal-header">
        	<span class="close">&times;</span>
        	<h2>Sign Up</h2>
    	</div>
		<form class="sign-up" action="/users" method="post" data-remote="true" class="form-signin">
     		<div class="modal-body">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input id="username" name="user[username]" placeholder="Username" type="text" autofocus>
				<input id="password" name="user[password]" placeholder="Password" type="password">
      		</div>
      		<div class="modal-footer">
        		<button class="close" type="button">Close</button>
        		<input type="submit" class="Btn" id="sign-up" value="Sign Up »">
    		</div>
	    </form>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProKeys</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
  	<%= javascript_include_tag "application" %>
 	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
	<div id="nav_grid">
		<%= render partial: "layouts/navbar" %>
	</div>
	<div id="error_grid" class="margin">
		<%= render partial: "layouts/error" %>
	</div>
	
	<%= yield %>
</body>
</html>